server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://182.92.71.24:33061/k-blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: kblog
    driver-class-name: com.mysql.cj.jdbc.Driver
